- .travis.yml
Move to before running composer install, since it's too late after that fact.
> Fix composer validate position

- .travis.yml
- phpunit.xml.dist
See https://github.com/silverstripe/silverstripe-installer/pull/168
Removes non-versioned tests from suite, and fixes test build.
> Update build dependencies

- src/Versioned.php
- tests/php/VersionedTest.php
- tests/php/VersionedTest.yml
- tests/php/VersionedTest/ChangeSetTestObject.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/6258
> ENHANCEMENT Remove item from change sets when it's archived

- src/Versioned.php
See https://github.com/silverstripe/silverstripe-framework/issues/6085
> API Remove object class references

- src/ChangeSetItem.php
- src/Versioned.php
- tests/php/VersionableExtensionsTest/TestExtension.php
- tests/php/VersionedTest.php
- tests/php/VersionedTest/WithIndexes.php
Tightening up DB index definitions
> Tighten up DB index definitions

- src/ChangeSet.php
- src/ChangeSetItem.php
- src/Versioned.php
- tests/php/ChangeSetTest.php
- tests/php/VersionedTest.php
Move Member::currentUser() => Security::getCurrentUser()
> [WIP] Authenticator Refactor

- src/DataDifferencer.php
- tests/php/DataDifferencerTest.php
- tests/php/DataDifferencerTest/TestObject.php
Merge up from 3 branch for https://github.com/silverstripe/silverstripe-framework/issues/7025
> [SS-2017-004] FIX DataDifferencer doesnt correctly cast data

- .upgrade.yml
- tests/php/DataDifferencerTest.php
Part of https://github.com/silverstripe/silverstripe-framework/issues/7104
> Update code for upgrader

- src/Versioned.php
- tests/php/VersionedTest.php
In preparation for https://github.com/silverstripe/silverstripe-framework/issues/6803
> FIX Use merge instead of update for config calls

- composer.json
- src/ChangeSetItem.php
- src/Versioned.php
- tests/php/ChangeSetTest.php
- tests/php/ChangeSetTest/MidObject.php
- tests/php/VersionedCascadeDeletesTest.php
- tests/php/VersionedCascadeDeletesTest.yml
- tests/php/VersionedCascadeDeletesTest/ChildObject.php
- tests/php/VersionedCascadeDeletesTest/GrandChildObject.php
- tests/php/VersionedCascadeDeletesTest/ParentObject.php
- tests/php/VersionedCascadeDeletesTest/RelatedObject.php
Fixes #23
Requires https://github.com/silverstripe/silverstripe-framework/pull/7257
> API Introduce cascade_deletes config feature for recursive delete and unpublish

- src/DataDifferencer.php
See https://github.com/silverstripe/silverstripe-framework/pull/7298
> Replace use of Configurable stat() with config()->get(), will be deprecated in future

- lang/en.yml
- src/ChangeSet.php
- tests/php/ChangeSetTest.php
Resolves: 
https://github.com/silverstripe/silverstripe-campaign-admin/issues/38
https://github.com/silverstripe/silverstripe-admin/issues/166
> New published fields for ChangeSet

- src/ChangeSetItem.php
- tests/php/ChangeSetTest.php
Practical use case of this example: In userforms, if you delete a field and publish the parent, now the deleted field is unpublished via changeset.
> ENHANCEMENT Ensure that partial deletes of cascade_deletes get unpublished

- .travis.yml
- src/ChangeSetItem.php
- tests/php/ChangeSetTest.php
- tests/php/ChangeSetTest.yml
- tests/php/ChangeSetTest/MidObject.php
- tests/php/ChangeSetTest/UnversionedObject.php
Replaces https://github.com/silverstripe/silverstripe-versioned/pull/42 with some tests
> BUG Fix issue with cascading deletes to unversioned objects

- src/ChangeSet.php
- src/ChangeSetItem.php
Required for https://github.com/silverstripe/silverstripe-campaign-admin/pull/58
> ENHANCEMENT Better sync behaviour

- phpunit.xml.dist
Fixes regressions for https://github.com/silverstripe/silverstripe-framework/issues/7405
Restart after https://github.com/silverstripe/silverstripe-framework/pull/7427
> Update CI path

- _config/versionedextension.yml
- src/VersionableExtension.php
- src/Versioned.php
- tests/php/DataDifferencerTest.php
- tests/php/VersionableExtensionsTest/TestExtension.php
- tests/php/VersionedManyManyThroughListTest/VersionedItem.php
- tests/php/VersionedOwnershipTest/Attachment.php
- tests/php/VersionedOwnershipTest/Related.php
- tests/php/VersionedTest.php
- tests/php/VersionedTest/SingleStage.php
- tests/php/VersionedTest/WithIndexes.php
Parent story: https://github.com/silverstripe/silverstripe-framework/issues/7382
Requires https://github.com/silverstripe/silverstripe-framework/pull/7437
> API Support stateless versioned extensions

- _config/versionedextension.yml
- src/MemberExtension.php
- tests/php/VersionedTest.php
Fixes #62 
Requires https://github.com/silverstripe/silverstripe-framework/pull/7547
> FIX Reset reading stage when user logs out of the CMS

- src/Versioned.php
According to `SiteTreeExtension` the `onBeforePublish` and `onAfterPublish` extension hooks expect the `$original` published object to be passed as an argument:
https://github.com/silverstripe/silverstripe-cms/blob/c7214b4dcde6ac2e14ca5d451e17e96dfc739651/code/Model/SiteTreeExtension.php#L14-L30
This patch restores this functionality
> FIX Provide expected argument to onBefore/AfterPublish hooks

- src/Versioned.php
A port of https://github.com/silverstripe/silverstripe-framework/pull/7661
> Port of silverstripe/framework#7661

- src/VersionedGridFieldItemRequest.php
Issue: https://github.com/silverstripe/silverstripe-versioned/issues/51
> ENHANCEMENT Add version status badge in gridfield detail view

- _config/versionedgridfield.yml
- src/VersionedGridFieldState.php
- src/VersionedGridFieldStateExtension.php
Main story https://github.com/silverstripe/silverstripe-versioned/issues/87
Also adds in status for published records.
@clarkepaul can you please eyeball this and tell me if this is the correct gridfield style?
> API Refactor GridFieldVersionedState into versioned module

- tests/php/GraphQL/Operations/ReadVersionsTest.php
- tests/php/GraphQL/Resolvers/ApplyVersionFiltersTest.php
Clean up tests per Dan's recommendations https://github.com/silverstripe/silverstripe-versioned/pull/83#issuecomment-361739502
> MINOR: Clean up tests

- src/GraphQL/Operations/CopyToStage.php
- src/GraphQL/Operations/Publish.php
- src/GraphQL/Operations/PublishOperation.php
- src/GraphQL/Operations/ReadVersions.php
- src/GraphQL/Operations/Unpublish.php
- src/GraphQL/Types/CopyToStageInputType.php
- src/GraphQL/Types/VersionedInputType.php
- src/GraphQL/Types/VersionedQueryMode.php
- src/GraphQL/Types/VersionedStage.php
- src/GraphQL/Types/VersionedStatus.php
Fixes currently failing framework build
> BUG Prevent versioned crashing in absence of graphql module

- src/VersionedGridFieldDetailForm.php
- src/VersionedGridFieldItemRequest.php
- tests/php/VersionedGridFieldItemRequestTest.php
Resolves https://github.com/silverstripe/silverstripe-versioned/issues/71
> ENHANCEMENT: Better communication of $owns behaviour

- _config/versionedownership.yml
- src/VersionedGridFieldItemRequest.php
Also don't use "Apply changes" for non-owners
Follow up to https://github.com/silverstripe/silverstripe-versioned/pull/107
> BUG Remove unnecessary recursivePublish() calls

- _config/versionedgridfield.yml
- src/VersionedGridFieldItemRequest.php
- tests/php/VersionedGridFieldItemRequestTest.php
- tests/php/VersionedGridFieldItemRequestTest/UnversionedObject.php
- tests/php/VersionedGridFieldItemRequestTest/UnversionedOwner.php
- tests/php/VersionedGridFieldItemRequestTest/VersionedObject.php
- tests/php/VersionedGridFieldTest/TestController.php
I've noticed that this component was treating "save" as "save and publish"
> BUG Prevent versioned records self-publishing

- src/GraphQL/Operations/CopyToStage.php
- src/GraphQL/Operations/PublishOperation.php
- src/GraphQL/Operations/ReadVersions.php
ENHANCEMENT Make all operations implement ResolverInterface
Requires https://github.com/silverstripe/silverstripe-graphql/pull/138
> BUG Fix createArgs() for Versioned graphql operations

- tests/php/DataDifferencerTest.php
So we can use dist version of assets module for testing
> Update reference to TestAssetStore

- src/Versioned.php
API Support new extend*() format for extension methods
Requires https://github.com/silverstripe/silverstripe-framework/pull/7752
> API Remove deprecated 5.0 methods, Fix can* extension hooks

- src/ChangeSetItem.php
- src/VersionedGridFieldDetailForm.php
- src/VersionedGridFieldItemRequest.php
- tests/php/ChangeSetTest.php
- tests/php/ChangeSetTest.yml
- tests/php/ChangeSetTest/MidObject.php
- tests/php/ChangeSetTest/UnstagedObject.php
Parent issue: https://github.com/silverstripe/silverstripe-versioned/issues/115
> BUG Fix behaviour towards versioned but unstagable records

- src/ChangeSetItem.php
- src/VersionedGridFieldItemRequest.php
- tests/php/ChangeSetItemTest.php
- tests/php/ChangeSetItemTest/UnstagedObject.php
- tests/php/ChangeSetTest.php
- tests/php/ChangeSetTest.yml
- tests/php/ChangeSetTest/MidObject.php
- tests/php/ChangeSetTest/UnstagedObject.php
Parent issue: https://github.com/silverstripe/silverstripe-versioned/issues/115
> BUG Fix behaviour towards versioned but unstagable records (4.1 specific)

- src/VersionedGridFieldItemRequest.php
- tests/php/VersionedGridFieldItemRequestTest.php
- tests/php/VersionedGridFieldItemRequestTest/UnversionedObject.php
- tests/php/VersionedGridFieldItemRequestTest/UnversionedOwner.php
- tests/php/VersionedGridFieldItemRequestTest/VersionedOwner.php
Resolves https://github.com/silverstripe/silverstripe-versioned/issues/26
> Add warning when unpublishing owned records

- src/ChangeSetItem.php
- src/Versioned.php
- tests/php/ChangeSetTest.php
- tests/php/GraphQL/Operations/CopyToStageTest.php
- tests/php/VersionedCascadeDeletesTest.php
- tests/php/VersionedDeletedVersionsTest.php
- tests/php/VersionedDeletedVersionsTest/CompanyOfficeLocation.php
- tests/php/VersionedDeletedVersionsTest/CompanyPage.php
- tests/php/VersionedDeletedVersionsTest/GalleryBlock.php
- tests/php/VersionedDeletedVersionsTest/GalleryBlockItem.php
- tests/php/VersionedDeletedVersionsTest/GalleryBlockPage.php
- tests/php/VersionedDeletedVersionsTest/OfficeLocation.php
- tests/php/VersionedManyManyThroughListTest.php
- tests/php/VersionedManyManyThroughListTest/VersionedObject.php
- tests/php/VersionedTest.php
Resolves https://github.com/silverstripe/silverstripe-versioned/issues/93
> WIP: Include all versions in archive mode

- src/GraphQL/Extensions/DataObjectScaffolderExtension.php
- src/GraphQL/Extensions/SchemaScaffolderExtension.php
- tests/php/GraphQL/Extensions/ReadExtensionTest.php
- tests/php/GraphQL/Extensions/ReadOneExtensionTest.php
- tests/php/GraphQL/Extensions/SchemaScaffolderExtensionTest.php
- tests/php/GraphQL/Operations/CopyToStageTest.php
- tests/php/GraphQL/Operations/PublishTest.php
- tests/php/GraphQL/Operations/UnpublishTest.php
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/95
> Compliance with new graphql Schema class

- src/RecursivePublishable.php
Parent story https://github.com/silverstripe/silverstripe-versioned/issues/75
> BUG Don't crash on polymorphic ownership

- src/Versioned.php
- tests/php/VersionedTest.php
ENHANCEMENT Allow cleanupVersionedOrphans to be disabled
BUG Fix cleanupVersionedOrphans breaking on table case change
BUG Use single query for deleting orphans for better performance on huge datasets
Fixes #139
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7944
For peer review by @mateusz please who raised the original issues.
With a single SQL DELETE we should now be able to cleanup much larger datasets without error, although the config is now available if you wish to disable it anyway.
> ENHANCEMENT / BUG Improve cleanupVersionedOrphans

- src/ChangeSet.php
- src/ChangeSetItem.php
- src/GraphQL/Operations/CopyToStage.php
- src/GraphQL/Operations/PublishOperation.php
- src/RecursivePublishable.php
- src/Versioned.php
- tests/php/ChangeSetTest.php
- tests/php/VersionedOwnershipTest.php
- tests/php/VersionedOwnershipTest/Subclass.php
- tests/php/VersionedTest.php
Parent story https://github.com/silverstripe/silverstripe-versioned/issues/94
> API Implement rollbackRecursive() / rollbackSingle()

- src/GraphQL/Operations/CopyToStage.php
- src/GraphQL/Operations/Publish.php
- src/GraphQL/Operations/PublishOperation.php
- src/GraphQL/Operations/ReadVersions.php
- src/GraphQL/Operations/Unpublish.php
- tests/php/GraphQL/Extensions/DataObjectScaffolderExtensionTest.php
Parent story https://github.com/silverstripe/silverstripe-graphql/issues/142
Requires https://github.com/silverstripe/silverstripe-graphql/pull/151
> Update for graphql 2.0 changes

- src/VersionedGridFieldItemRequest.php
- tests/php/VersionedGridFieldItemRequestTest.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/8029
> Use record ID to detect new item for button label

- src/VersionedGridFieldStateExtension.php
> Prevent two VersionedGridFieldState being added by the extension

- src/ChangeSet.php
- tests/php/Caching/ProxyCacheFactoryFake.php
- tests/php/Caching/ProxyCacheFactoryTest.php
- tests/php/VersionedTest.php
Related https://github.com/silverstripe/silverstripe-framework/issues/8182
> BUG Fix unit tests for 4.2 core regressions

- src/ChangeSet.php
- src/VersionedGridFieldDetailForm.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/8136
Requires https://github.com/silverstripe/silverstripe-framework/pull/8164 to be merged first.
manually tested.
> BUG Prevent custom item handler from being overridden

- src/Versioned.php
Add Versioned.mode latest_version_single for a faster querying of single versioned records, add index to WasDeleted
> Add "latest_version_single" as a "Versioned.mode"

- _config/graphql.yml
- src/GraphQL/Extensions/DeleteExtension.php
Fixes dnadesign/silverstripe-elemental#678
> FIX Ensure dataobjects are unpublished during the delete mutation

- _config/graphql.yml
- src/GraphQL/Extensions/DeleteExtension.php
- src/VersionedGridFieldItemRequest.php
- tests/php/VersionedGridFieldItemRequestTest.php
Resolves https://github.com/silverstripe/silverstripe-admin/issues/904
> FIX make the actions consistent on the grid field items to what they look like on pages

- composer.json
See [silverstripe-cms#2521](https://github.com/silverstripe/silverstripe-cms/issues/2521) for context.
> FIX Update core requirement to 4.5 series

- .gitignore
- tests/php/DataDifferencerTest.php
- tests/php/GraphQL/Extensions/ReadExtensionTest.php
- tests/php/GraphQL/Extensions/ReadOneExtensionTest.php
- tests/php/GraphQL/Operations/CopyToStageTest.php
- tests/php/GraphQL/Operations/PublishTest.php
- tests/php/GraphQL/Operations/ReadVersionsTest.php
- tests/php/GraphQL/Operations/RollbackTest.php
- tests/php/GraphQL/Operations/UnpublishTest.php
- tests/php/GraphQL/Resolvers/ApplyVersionFiltersTest.php
- tests/php/VersionedGridFieldItemRequestTest.php
Depends on https://github.com/silverstripe/silverstripe-framework/pull/9443
> Update tests for phpunit8

- .travis.yml
- lang/en.yml
* https://github.com/silverstripeltd/product-issues/issues/177
> Merge up 1.6 branch + update travis to target x-dev branches #401

- src/VersionedTableDataQueryExtension.php
- tests/php/UnstagedStagedRelationTest.php
> Fix for issue #283 Only add _Live to tables that have stages

- src/Versioned.php
* no functional changes
* new extension points (`get_versionnumber_by_stage`, `get_latest_version` and `isArchived`)
https://github.com/tractorcow-farm/silverstripe-fluent/pull/639
> NEW: Extension points for version lookup and archive state.

- src/Versioned.php
* 3 new extension points added
* no change in functionality
https://github.com/tractorcow-farm/silverstripe-fluent/pull/639
> NEW: Extension points for isOnDraft() and isPublished().

- src/VersionedGridFieldItemRequest.php
> FIX: Remove canPublish check for users to see unpublish button (fixes #300)

- src/ChangeSetItem.php
- src/Versioned.php
- src/Versioned_Version.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/1915
> ENH Replace E_USER_ERROR errors with exceptions

- lang/de.yml
- lang/en.yml
- lang/eo.yml
- lang/fi.yml
- lang/pl.yml
- lang/sl.yml
Reverts
https://github.com/silverstripe/silverstripe-versioned/commit/05d1720bb2c68dceb49fb8dd4a3188a37c4ebed8
https://github.com/silverstripe/silverstripe-versioned/commit/b78ac789824717eea722f513a1a2b0e47584f1ae
> Revert translation updates

- _config/graphql_plugins.yml
See: https://github.com/silverstripe/silverstripe-graphql/pull/327
> NEW compatibility with new stateless plugins

- tests/php/GraphQL/Plugins/VersionedDataObjectPluginTest.php
Create schemas using factory so that auto-discovery configuration is applied
> MNT Create schemas using factory

- src/GraphQL/Operations/CopyToStageCreator.php
- src/GraphQL/Plugins/UnpublishOnDelete.php
- src/GraphQL/Plugins/VersionedDataObject.php
- src/GraphQL/Plugins/VersionedRead.php
- src/GraphQL/Resolvers/VersionedResolver.php
- tests/php/GraphQL/Plugins/VersionedDataObjectPluginTest.php
- tests/php/GraphQL/Plugins/VersionedReadTest.php
- tests/php/GraphQL/Resolvers/VersionedResolverTest.php
Use new `UserContextProvider`, no more `defaultResolver`
Depends on https://github.com/silverstripe/silverstripe-graphql/pull/352
> NEW: Compatibility with GraphQL 4 changes

- src/RecursivePublishable.php
> Unset sort for subquery if we're using MS SQL database

- composer.json
Issue https://github.com/silverstripe/silverstripe-versioned/issues/332
> DEP Require-dev graphql ^3.5 or ^4

- tests/php/VersionedTest.php
Issue https://github.com/silverstripe/recipe-cms/issues/47
> MNT Update tests to use logInAs()

- src/GraphQL/Plugins/VersionedDataObject.php
Fixes https://github.com/silverstripe/silverstripe-graphql/issues/404
> BUGFIX: Ensure scalar plugin is assigned to Version field

- composer.json
- tests/php/VersionedTest.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10019
> MNT Remove polyfill

- src/DataDifferencer.php
Also remove cloning where it isn't necessary.
@michalkleiner per our discussion starting in [this comment](https://github.com/silverstripe/silverstripe-versioned/pull/354#issuecomment-1068788809) on #354.
I didn't make a separate method in the end because the list of diffed fields is exactly what is returned by `changedFieldNames`.
> ENH: Refactor DataDifferencer to reduce duplicate code.

- src/GraphQL/Operations/AbstractPublishOperationCreator.php
- src/GraphQL/Operations/CopyToStageCreator.php
- src/GraphQL/Operations/RollbackCreator.php
- src/GraphQL/Plugins/UnpublishOnDelete.php
- src/GraphQL/Plugins/VersionedDataObject.php
- src/GraphQL/Plugins/VersionedRead.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10250
> ENH Fix deprecation issues for PHP 8.1 compatibility

- src/Versioned.php
> FIX comparing versions when class changes (#363)

- .codecov.yml
- .github/workflows/ci.yml
- .github/workflows/keepalive.yml
- .travis.yml
- README.md
- phpunit.xml.dist
Issue https://github.com/silverstripeltd/product-issues/issues/570
> MNT Standardise modules
