silverstripe/silverstripe-versioned

tests/php/VersionedTest.php

augmentDatabase is added via a DataExtension. If there's more than one extension defining it, this test was only running one of them.

FIX augmentDatabase should be called via extend(), not dirrectly

---

_config/versionedtests.yml
src/Dev/VersionedTestState.php
src/Versioned.php
src/VersionedRequestFilter.php
tests/php/VersionedLazyLoadingTest.php
tests/php/VersionedTest.php
tests/php/VersionedTest/AnotherSubclass.php

Main issue: https://github.com/silverstripe/silverstripe-framework/issues/6681
See https://github.com/silverstripe/silverstripe-framework/pull/7037 for framework pull request

[WIP] App object

---

lang/en.yml
src/VersionedGridFieldItemRequest.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/6582

FIX Remove legacy sprintf style translations in favour of placeholders

---

src/ChangeSetItem.php
tests/php/ChangeSetTest.php
tests/php/ChangeSetTest.yml

Regardless of whether they have been published
So implicit items are only removed if it is no longer implicitly included.

Enhancement show all implicit objects

---

src/Versioned.php
tests/php/VersionedOwnershipTest.php
tests/php/VersionedOwnershipTest/Subclass.php

API Introduce new hasPublishedOwners() method to toggle warnings prior to unpublish
Fixes #25

API Don’t unpublish owners when unpublishing children

---

.travis.yml
composer.json
src/VersionedGridFieldDetailForm.php
src/VersionedGridFieldItemRequest.php
tests/php/ChangeSetItemTest/VersionedObject.php
tests/php/VersionedGridFieldTest.php
tests/php/VersionedGridFieldTest/TestController.php
tests/php/VersionedTest.php
tests/php/VersionedTest/TestObject.php

Change GridfieldDetailForm to be opt-in

---

src/ChangeSetItem.php

Use case: Localised dataobjects may need to declare themselves as `CHANGED` if they are unpublished in the current locale, but are published in some other locale. An additional locale-gnostic check must be made within the extension to ChangeSetItem.

ENHANCEMENT Allow extensions to clarify change type for versioned objects

---

src/VersionedGridFieldDetailForm.php

If a developer customises the ItemRequest don’t override it as long as it is already a versioned item hander.

FIX Don’t override ItemRequest if already versioned

---

phpunit.xml.dist

Currently the test stubs are included in code coverage reports, see: https://codecov.io/gh/silverstripe/silverstripe-versioned/tree/master/tests/php
Adding a standard whitelist to exclude the tests dir

Add code coverage whitelist to ensure stubs are not covered

---

.travis.yml
composer.json
tests/php/ChangeSetTest.php
tests/php/VersionedTest.php

See silverstripe/silverstripe-framework#7653
Requires silverstripe/silverstripe-framework#7716
The extra assertions are because the tests originally don't assert anything, which PHPUnit 7.x treats as a "risky" test.

API Upgrade to PHPUnit 7, increase minimum PHP version to 7.1

---

src/RecursivePublishable.php

Parent story https://github.com/silverstripe/silverstripe-versioned/issues/28
Ensures that, in the absence of cascade_duplications() versioned will use `owns` to infer duplications.

API Ensure that duplications fail over to owned objects

---

src/ChangeSet.php
src/ChangeSetItem.php
src/Versioned.php
tests/php/ChangeSetTest.php
tests/php/ChangeSetTest/Permissions.php

ENHANCEMENT Modify permission checks to require outside invocation instead of verifying internally (ref: https://docs.silverstripe.org/en/4/developer_guides/model/permissions/)
Fixes #112 
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7837
Note: It would be good for a @silverstripe/core-team to confirm my thinking regarding the permissions (see the link above). I feel that we should stick with the convention of requiring user code to invoke those permission checks, rather than internally failing if any are denied, causing exceptions.

BUG Prevent nested permissions from breaking recursive publishing

---

src/Versioned.php
tests/php/VersionedTest.php

See warning on PHPDoc
Fixes https://github.com/tractorcow/silverstripe-fluent/issues/313

BUG Fix doRollbackTo() writing old / unsaved version over restored version

---

src/VersionedGridFieldItemRequest.php

Allows other modules to push badges to the breadcrumbs as well as versioned, which would overwrite anything that was already set. NB: other modules must append or prepend whatever was there first (from this module).
Closes silverstripe/silverstripe-admin#439

NEW Allow CMS breadcrumb badge to be extended

---

src/GraphQL/Extensions/DataObjectScaffolderExtension.php

Before this change `Published` in the Versions list is always returning null. My assumption is that it's not mapping to the property because the prop name is `WasPublished`, which is what `Versioned_Version::Published()` checks and return the value of.

FIX Resolve Published version field to Versioned_Version::Published() correctly

---

src/GraphQL/Resolvers/ApplyVersionFilters.php

When writing a query like this:
```
query readOnePage{
readOnePage(Versioning:{
Mode: STATUS
Status:[DRAFT,PUBLISHED]
}, ID:2){
```
You get an error: `"message": "Invalid statuses provided",`
This PR adds the condition for "published" which was missing.

FIX Add missing published state filter

---

tests/php/GraphQL/Operations/ReadVersionsTest.php

This gets tests green again.
1. Fixes a test assumption that is wrong since `Versioned_Version` was removed and `Versions` now returns a `DataList` and not an `ArrayList`
2. It appears the order of records is reversed from what the test expected - is this right or is this a genuine bug?

FIX Get tests green again

---

.travis.yml
src/GraphQL/Extensions/DataObjectScaffolderExtension.php
src/Versioned.php
src/Versioned_Version.php
tests/php/VersionedTest.php

This surfaces whether each version is the current live version and the current/latest draft or modified version.
Required for #37

NEW Add isLiveVersion and isLatestDraftVersion to Versioned and GraphQL DataObject scaffolding

---

src/Versioned.php

Fixes https://github.com/silverstripe/silverstripe-versioned/issues/124
Once merged, merge up to master to fix cms master tests.
The problem is that the `Was*` fields were cast to default_cast (varchar), which treats "0"(string) as non-falsey. PDO connections use strings for int results, hence the tests would pass on non-pdo connectors.
Casting to boolean correctly ensures the correct cast.

BUG Ensure extra fields have correct casting

---

src/ReadingMode.php
src/Versioned.php
tests/php/ReadingModeTest.php

Reference; https://github.com/dnadesign/silverstripe-elemental/pull/215
This change will prevent invalid stages creeping into the current mode, causing hard-to-track down errors.

ENHANCEMENT Ensure invalid stage values are thrown as exceptions

---

src/RecursivePublishable.php
src/VersionedGridFieldItemRequest.php
tests/php/VersionedGridFieldItemRequestTest.php
tests/php/VersionedOwnershipTest.php

Now that `FileTracking` is applied to all dataobjects, this returns a lot of false positives, creating an ominous "Apply changes (draft /modified items will be published)" warning. This is bad UX and is also stuffing up Behat tests, e.g. https://travis-ci.org/silverstripe/silverstripe-framework/jobs/379449536#L917
`findOwned()` is not very performant, but open to suggestions.
Parent issue https://github.com/silverstripe/silverstripe-framework/issues/8029

Only add versioned buttons when owned objects actually exist

---

_config/graphql.yml
src/GraphQL/Extensions/ManagerExtension.php
src/GraphQL/Operations/Publish.php
src/GraphQL/Operations/PublishOperation.php
src/GraphQL/Operations/Unpublish.php

In adherence to new multi-schema work.
Resolves: https://github.com/silverstripe/silverstripe-graphql/issues/158

Add versioned graphql types via extension instead of direct YAML

---

src/VersionedHTTPMiddleware.php

"permission failure" message contains HTML which currently displays as a plaintext. This changeset adds casting to the message so it can display properly.

Added missing HTML casting on the "permission failure" error message.

---

src/VersionedStateExtension.php
tests/php/VersionedStateExtensionTest.php

Add a condition so we don't try to add Stage URL param to LeftAndMain links.
Fixes https://github.com/silverstripe/silverstripe-admin/issues/607

FIX Do not update LeftAndMain link with Stage param

---

src/Versioned.php
tests/php/GridFieldRestoreActionTest.php

GridFieldRestoreActionTest::testDontShowRestoreButtons via TestObject::canRestoreToDraft was causing infinite loops and exceeding memory limits. The Versioned::canRestoreToDraft method calls itself via $owner->extendedCan(canRestoreToDraft, $member), but it never passes more than two arguments. This patch fixes the loose recursion check.
This should get the SS5 tests green.

FIX Detection of extendedCan now works preventing infinite loops in unit tests

---

src/Versioned.php
tests/php/VersionedNumberCacheTest.php
tests/php/VersionedTest.php

When draft pages are rendered in the treeview, an attempt to look up
their live Version # is made. This leads to a cache miss and a
subsequent query for each record.
This change marks a cache as “complete” when all records of a given
stage are pre-cached. This will suppress the record-specific query
in the case of a cache miss.
* silverstripe/silverstripe-cms#2250

FIX: Performance optimisation for draft pages in treeview

---

src/RecursivePublishable.php

DataObject::inferReciprocalComponent  cannot be called on object without IDs. There is currently no checks if owner has a proper id, which could result on errors.
Also use $owner instead of $this->owner for consistency in the function.
to be honest, I'm not sure how I managed to do that, but this extra check cannot hurt in my opinion.

fix inferReciprocalComponent called on unsaved

---

src/Versioned.php
tests/php/VersionedNumberCacheTest.php

Doesn't do anything without https://github.com/silverstripe/silverstripe-framework/pull/8395

FIX: Use Hierarchy::prepopulateTreeDataCache() in CMS.

---

_config/graphql.yml
src/GraphQL/Operations/CopyToStage.php
src/GraphQL/Operations/Rollback.php
tests/php/GraphQL/Operations/Rollback/FakeDataObjectStub.php
tests/php/GraphQL/Operations/RollbackTest.php

Fixes #190 . This is a NEW targetted at 1.3 because it's fixing silverstripe/silverstripe-cms#2326
I've also marked the "CopyToStage" mutation as internal because it's quite low level and probably won't do all that you would want.

NEW Adding GraphQL operation scaffolder for rollbackRecursive on versioned objects

---

src/ChangeSet.php
src/RecursivePublishable.php
tests/php/ChangeSetTest.php
tests/php/ChangeSetTest/ChangeSetSyncStub.php

Provides tiny incy wincy performance boost when doing a publish recursive. Basically, if you just built a change set, you can safely assume it's in sync. So I added a flag to the publish method on the ChangeSet that allow you to bypass the sync validation.
* #189

MINOR Bypass sync validation on ChangeSet when it just got built

---

composer.json

Fixed wrong silver-stripe version requirement as detailed here:
https://github.com/silverstripe/silverstripe-versioned/issues/216

Fixed Wrong Silverstripe Requirement

---

src/Versioned.php

This part of the docblock is misleading - since it's part of Versioned it inherently only applies to versioned objects.

DOCS Remove misleading comment about Versioned::writeWithoutVersion() acting on objects without versioning

---

tests/php/VersionedTest.php
tests/php/VersionedTest/TestObject.php

Created as part of looking into 
https://github.com/silverstripe/silverstripe-framework/issues/3557
but the test confirmed that no further changes are needed.
Notably, this test validates the creation of an extra Versions entry
on publication as designed behaviour, which appears to be the case.

MINOR: Add test to validate writeWithoutVersioned

---

src/Versioned.php

```
ERROR [Emergency]: Uncaught Error: Call to a member function getQueryParam() on null
```
Found the error during upgrade to SS4 on Step 11 migrating files with `dev/tasks/MigrateFileTask`. 
Installed packages include:
`silverstripe/framework: 4.4.x-dev`
`silverstripe/versioned: 1.4.x-dev`
`silverstripe/fulltextsearch: 3.4.2`
The error was triggered by the fulltextsearch module, `SearchIndex` on line 632 `singleton($step['class'])->extend('augmentSQL', $sql);`
I am aware that there's a [PR](https://github.com/silverstripe/silverstripe-fulltextsearch/pull/239) to fix this in fulltextsearch but the signature of the method causes it to fail by default which is IMO not a good practice. If `$dataQuery` is nullable due to legacy reasons, still we can't assume that this is always set …

FIX call to getQueryParam() on null error

---

composer.json
src/GridFieldArchiveAction.php
src/GridFieldRestoreAction.php

This change must be released as a 1.3.x patch tag, then the Composer constraint can be bumped back again to where it was. This will fix cases where Composer installs silverstripe/versioned ~1.3.0 on older SilverStripe 4.0/4.1 projects, which has a backwards compatibility break in it.
The change here allows the code to be backwards compatible with older versions. Once tagged it can be bumped and re-tagged in future in the same release line without concerns for the same B/C break.
Issue: https://github.com/silverstripe/silverstripe-versioned/issues/230
Note that we've already decided it's OK to stop releasing core modules in lock step with each other - see https://github.com/silverstripe/silverstripe-framework/issues/8970

FIX Revert framework constraint bump and add easly returns when non B/C interface does not exist

---

composer.json
src/GridFieldArchiveAction.php
src/GridFieldRestoreAction.php

This reverts commit 5df7f4f2708efe98daa6c2be8f0d5a2de6b0742d.
The previous commit has been released in 1.3.4, so we can restore the previous state from now on.
Issue: https://github.com/silverstripe/silverstripe-versioned/issues/230

Revert "FIX Revert framework constraint bump and add easly returns when non B/C interface does not exist"

---

src/RecursivePublishable.php

The fix allows classes extending RecursivePublishable to use `lookupReverseOwners`.
Currently, those aren't always explicitly registered as extensions and as such `DataObject::has_extension` may return false even if RecursivePublishable is there, but the particular calling extension is not.
`DataObject::has_extension` checks for deriving classes internally (unless a third parameter given).
https://github.com/silverstripe/silverstripe-versioned/issues/72

FIX lookupReverseOwners to work in deriving classes

---

src/Versioned.php

This is a performance "fix" that should have no impact on the existing functionality.
This is a follow-up to #213 . There was concern in that PR that the solution we came up with (changing the non-correlated subquery to a correlated one) had too many performance concerns. The suggestion was provided to "promote" certain conditions from the outer query to the inner join. The only condition that can be promoted is a filter on the primary key of the base table. This PR adds that which adds a small performance improvement.
I've also re-added the functionality from #213 but it relies on a hook added in silverstripe/silverstripe-framework#8915 or a config setting. In my large project I found zero scenarios where the inner join was more performant than the condition - and it is ~5s (browsing to …

FIX Implemented various options to improve archive query performance

---

src/Versioned.php

These methods are already removed in 5.x and are in the changelog as removals, we missed a deprecation notice though.

API Add deprecation warnings to Versioned::VersionsList() and allVersions()

---

src/Versioned.php

There are instances where you want to do actions after versioned has written the delete version.
An example of this is wanting to take a snapshot of a dataobject after it's been deleted. You'd currently get the wrong/correct version number depending on when the extension runs

Allow actions to be taken after versioned has recorded a delete

---

src/GridFieldArchiveAction.php

The archive action is set to take the place of the delete button,
considering that when a published item is deleted (i.e. from the
draft table) then it cannot be unpublished as no interface exists
to do so.
However this was having the unintended affect of removing objects
people wished to only remove from a relationship list, as the
archive action did not account for whether the delete action intends
to remove the related object, or the link to it (the relationship).
This is most easily remedied by providing the user with both options.
It may not be the best user experience, but is the most flexible.
Resolves #200

FIX archive relationships, not related objects

---

.travis.yml
src/Versioned.php

`WasDraft` didn't exist in SilverStripe 3. In most cases it will be set to `true`. Exception are when archiving a record or when publishing directly to live.
History view breaks in most cases when looking at records from SS3, because WasDraft default to false.
By default it to true we provided a better representation of the SilverStripe 3 data and we fix the history view.
Note that this will only fix new migration, not old one.
* https://github.com/silverstripe/silverstripe-versioned-admin/issues/100

Default Was Draft to true

---

_config/versionedextension.yml
src/VersionedTableDataQueryExtension.php
tests/php/VersionedTableTest/House.php
tests/php/VersionedTableTest/HouseVisit.php
tests/php/VersionedTableTest/Roof.php
tests/php/VersionedTableTest/VersionedTableTest.php
tests/php/VersionedTableTest/VersionedTableTest.yml
tests/php/VersionedTableTest/Visitor.php
tests/php/VersionedTableTest/WoodenRoof.php

* `DataQuery::applyRelation` now supports versioned tables
* `ManyManyThroughList` no longer leaks draft content
https://github.com/silverstripe/silverstripe-versioned/issues/254
https://github.com/silverstripe/silverstripe-framework/pull/9386
Split from https://github.com/silverstripe/silverstripe-framework/pull/8856

Added missing table versioning

---

src/GraphQL/Resolvers/ApplyVersionFilters.php
tests/php/GraphQL/Resolvers/ApplyVersionFiltersTest.php

This is useful for augmenting methods which return a DataObject
rather than a DataList, with their own internal querying logic.
The most common example for this is SiteTree::get_by_link().
Note that I've split out the argument validation rather than duplicating it,
and throw exceptions for the bits which aren't supported in "reading mode"
(namely "state" and "latest"versions")

NEW Apply versioned filters to reading state

---

src/Versioned.php

* extension point uses undefined variable
* this doesn't throw only because it's passed as a reference
* in current situation this is effectively the same as always passing `null`
* following line of code can be used as a short term workaround until this fix comes through
* put following line into your extension code to determine the stage
```
$stage = Versioned::get_stage()
```
https://github.com/silverstripe/silverstripe-versioned/issues/277

BUG: Write to stage extension point params.

---

src/Versioned.php
tests/php/VersionedTest.php
tests/php/VersionedTest/TestObject.php

Fix for https://github.com/silverstripe/silverstripe-assets/issues/371
Co-authored-by: Maxime Rainville <maxime@silverstripe.com>

FIX Re-fetch DataObject when unpublishing to handle modified state

---

src/Versioned.php
tests/php/VersionedTest.php

The existing code did nothing useful - returning true all the time for
these cases. This patch fixes them be a more meaningful semantic, where
draft and published are treated as being the same stage.
isOnLiveOnly() will never be true in such cases, and isPublished() will
always be the same as isOnDraft().
To do:

FIX: Fix semantics of isPublished(), isArchived(), isOnDraft() for objects without draft/published stages

---

.gitignore
composer.json
tests/php/VersionedStateExtensionTest.php
tests/php/VersionedTest/TestObject.php

Decoupling modules so that versioned doesn’t rely on an arbitrary and
undefined subset of the CMS recipe nudges our architecture in the right
direction. A more successful decomposition of the recipe into packages
would ensure that there aren’t bidirectional or cyclic relationships
between packages, and instead they are arranged more into “layers”.
This patch means that you can test the module independently, like so:
* (clone module)
* composer install
* vendor/bin/phpunit
The test suit not longer relies on HTMLEditorField, which in practise
is not fully functional without admin. It also skips 
There is 1 test that appears to test a piece of LeftAndMain behaviour.
Arguably it should be refactored and placed there, but I’ve made it
skippable instead.
With that in place it tightens the …

FIX: Decouple test setup.

---

src/GraphQL/Extensions/DataObjectScaffolderExtension.php
src/GraphQL/Resolvers/ApplyVersionFilters.php
src/GraphQL/Types/VersionedQueryMode.php
src/Versioned.php
tests/php/GraphQL/Resolvers/ApplyVersionFiltersTest.php
tests/php/VersionedTest.php

See https://github.com/silverstripe/silverstripe-cms/issues/2448
* Save fields to archived version entries (previously these entries would save without any fields on them)
* Show archived/deleted version entries instead of filtering them out

Show the type of save that was performed for the record instead of just showing either Saved/Published.

---

composer.json

Rely on the framework requirements instead.
Resolves https://github.com/silverstripe/silverstripe-versioned/issues/321

MNT Remove explicit Symfony cache dependency

---

src/Caching/ProxyCacheAdapter.php

Fixes https://github.com/silverstripe/silverstripe-versionfeed/issues/59
This prevents logging pollution from people using `/changes` and `/allchanges` from the versionfeed module, as well as possibly some other use cases.
This happens because those particular endpoints attempt to cache an `ArrayList` of `SiteTree` which have a property `protected $creatableChildrenCache` which at serialize time is a `VersionedCacheAdapter extends ProxyCacheAdapter` which has a pool of caches that will throw an exceptions when they are attempted to be `serialized()`.  Those caches will `serialize()` objects before writing them to disk/memory, so presumably those exceptions are there to prevent it from adding itself to its own cache.
To replicate the error, install kitchen-sink which includes frameworktest …

FIX Prevent ProxyCacheAdapter contents from being serialized

---

lang/de.yml
lang/en.yml
lang/fi.yml
lang/pl.yml

Fixes: https://github.com/silverstripe/silverstripe-versioned-admin/issues/156
> This was a design mishap where it was updated in one place and not another causing inconsistent across the board when it was developed.

Improvement: Update Versioned Admin menu title to "Archive"

---

src/GraphQL/Plugins/VersionedDataObject.php
tests/php/GraphQL/Plugins/VersionedDataObjectPluginTest.php

versioned-admin is broken because of this. See: https://github.com/silverstripe/silverstripe-graphql/issues/309

BUGFIX: replace versions pagination, sort to fix versioned-admin

---

src/GraphQL/Resolvers/VersionFilters.php

Allow graceful failure to make implementation simpler (resolveVersionedRead)

MINOR: applyToReadingState should not throw.

---

composer.json
phpunit.xml.dist
tests/php/Caching/ProxyCacheFactoryTest.php
tests/php/ChangeSetTest.php
tests/php/DataDifferencerTest.php
tests/php/GraphQL/Legacy/Extensions/DataObjectScaffolderExtensionTest.php
tests/php/GraphQL/Legacy/Extensions/ReadExtensionTest.php
tests/php/GraphQL/Legacy/Extensions/ReadOneExtensionTest.php
tests/php/GraphQL/Legacy/Extensions/SchemaScaffolderExtensionTest.php
tests/php/GraphQL/Legacy/Operations/CopyToStageTest.php
tests/php/GraphQL/Legacy/Operations/PublishTest.php
tests/php/GraphQL/Legacy/Operations/ReadVersionsTest.php
tests/php/GraphQL/Legacy/Operations/RollbackTest.php
tests/php/GraphQL/Legacy/Operations/UnpublishTest.php
tests/php/GraphQL/Legacy/Resolvers/ApplyVersionFiltersTest.php
tests/php/GraphQL/Plugins/VersionedDataObjectPluginTest.php
tests/php/GraphQL/Plugins/VersionedReadTest.php
tests/php/GraphQL/Resolvers/VersionedFiltersTest.php
tests/php/GraphQL/Resolvers/VersionedResolverTest.php
tests/php/GridFieldArchiveActionTest.php
tests/php/GridFieldRestoreActionTest.php
tests/php/ReadingModeTest.php
tests/php/VersionedCascadeDeletesTest.php
tests/php/VersionedManyManyThroughListTest.php
tests/php/VersionedNumberCacheTest.php
tests/php/VersionedOwnershipTest.php
tests/php/VersionedTest.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10019
Currently required for framework on travis to run
Note: there's an [equivalent branch](https://github.com/silverstripe/silverstripe-versioned/tree/pulls/1%2Fsapphire-test-nine) on the silverstripe account because travis doesn't like pulling from non silverstripe repos defined in composer.json "repositories". This branch will be deleted once this approach has been proven to work
This PR and the branch on the silverstripe are likely to get out of sync

[WIP] API phpunit 9 support

---

src/Versioned.php
tests/php/VersionedTest.php

Right now if you call `allVersions` on a singleton DataObject, it will try to run a query ... which is nonsensical. This is causing grievances to our graphql `--no-database` build steps.
- ~~https://github.com/silverstripe/silverstripe-graphql/issues/445~~
- #353

Don't run queries when trying to retrieve versions for unsaved records

---

src/DataDifferencer.php

Ran into `__clone method called on non-object` when using the assets admin history view. Elsewhere in this class there are checks against this variable being falsey, so this is a consistent way to resolve it and allows the history view to render without issues.

FIX Return correct changed fields when fromRecord is null

---

tests/php/GraphQL/Fake/FakeResolveInfo.php
tests/php/GraphQL/Legacy/Extensions/ReadExtensionTest.php
tests/php/GraphQL/Legacy/Extensions/ReadOneExtensionTest.php
tests/php/GraphQL/Legacy/Operations/CopyToStageTest.php
tests/php/GraphQL/Legacy/Operations/PublishTest.php
tests/php/GraphQL/Legacy/Operations/ReadVersionsTest.php
tests/php/GraphQL/Legacy/Operations/RollbackTest.php
tests/php/GraphQL/Legacy/Operations/UnpublishTest.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

MNT Compatibility with webonyx/graphql-php v14

---

src/Versioned.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

ENH Various fixes for PHP 8.1 compatibility

---

_legacy/GraphQL/Extensions/DataObjectScaffolderExtension.php
_legacy/GraphQL/Operations/ReadVersions.php

Replaces the `new` keyword with `::create` and makes ReadVersions injectable.

FIX: Make ReadVersions injectable
